### ISSUE TITLE
lost brackets at math.Sqrt in wilson function

### ISSUE THREAD

**Issue by einpare** [alextanhongpin/go-rate#1]
lower := (phat + z*z/(2*n) - z*math.Sqrt(phat*(1-phat)+z*z/(4*n))/n) / (1 + z*z/n)

should be:
lower := (phat + z*z/(2*n) - z*math.Sqrt((phat*(1-phat)+z*z/(4*n))/n)) / (1 + z*z/n)
lost () at math.Sqrt

**Comment by alextanhongpin** [comment]
@einpare Thank you for noticing, I have fixed the code :)
